name: CI
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28
      - uses: actions/checkout@v3
      - name: Run linter
        run: deno lint
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28
      - uses: actions/checkout@v3
      - name: Run formatter
        run: deno fmt --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.28
      - uses: actions/checkout@v3
      - name: Run tests
        run: deno test
